<?php
//Config
$items = $block->getDataBlocks();

$display = $block->getProductWidget('display_type',null);
$numSlide = $block->getProductWidget('products_per_slide', 4);
$numScrollSlide = $block->getProductWidget('products_scroll_slide', 5);
$timeScrollSlide = $block->getProductWidget('time_scroll_slide', 2);
$numProduct = $block->getProductWidget('products_count', 10);
$page = $block->getProductWidget('show_pager', 0);
$numPage = $block->getProductWidget('products_per_page', 5);
$featured = $block->getProductWidget('featured', 1);

$count = 0;
?>

<div class="products wrapper grid products-grid">
    <ol class="products list items product-items <?php if($display == 'slide_products') echo "my-list"; ?>">
        <?php foreach ($items as $item) : ?>
            <?php if($featured == 1) : ?>
                <?php if($item['featured'] == 1) : ?>
                    <?php $imagePath = $block->getUrlImagePrd($item, 'image') ?>
                    <li class="item product product-item">
                        <div class="product-item-info" data-container="product-grid">
                            <a href="<?php echo $block->getUrl('product/product/detail') . 'id/' . $item['id']; ?>" class="product photo product-item-photo" tabindex="-1">
                                <span class="product-image-container" style="width:240px;">
                                    <span class="product-image-wrapper" style="padding-bottom: 125%;">
                                        <img class="product-image-photo" src="<?php echo $imagePath  ?>" max-width="240" max-height="300" alt="Name of product"></span>
                                </span>
                            </a>
                            <div class="product details product-item-details">
                                <strong class="product name product-item-name">
                                    <a class="product-item-link" href="<?php echo $block->getUrl('product/product/detail') . 'id/' . $item['id']; ?>">
                                        <?= $item['name'] ?></a>
                                </strong>
                                <div class="price-box price-final_price" data-role="priceBox" data-product-id="436" data-price-box="product-id-436"><span class="normal-price">
                                        <span class="price-container price-final_price tax weee">
                                            <span class="price-label">Giá : <?= $item['price'] ?></span>
                                            <span id="product-price-436" data-price-amount="45" data-price-type="finalPrice" class="price-wrapper "><span class="price"><?= $item['description'] ?></span></span>
                                        </span>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php 
                if(++$count >= $numProduct) break;
                ?>
                <?php endif; ?>
            <?php else: ?>
                <?php $imagePath = $block->getUrlImagePrd($item, 'image') ?>
                <li class="item product product-item">
                    <div class="product-item-info" data-container="product-grid">
                        <a href="<?php echo $block->getUrl('product/product/detail') . 'id/' . $item['id']; ?>" class="product photo product-item-photo" tabindex="-1">
                            <span class="product-image-container" style="width:240px;">
                                <span class="product-image-wrapper" style="padding-bottom: 125%;">
                                    <img class="product-image-photo" src="<?php echo $imagePath  ?>" max-width="240" max-height="300" alt="Name of product"></span>
                            </span>
                        </a>
                        <div class="product details product-item-details">
                            <strong class="product name product-item-name">
                                <a class="product-item-link" href="<?php echo $block->getUrl('product/product/detail') . 'id/' . $item['id']; ?>">
                                    <?= $item['name'] ?></a>
                            </strong>
                            <div class="price-box price-final_price" data-role="priceBox" data-product-id="436" data-price-box="product-id-436"><span class="normal-price">
                                    <span class="price-container price-final_price tax weee">
                                        <span class="price-label">Giá : <?= $item['price'] ?></span>
                                        <br>
                                        <span id="product-price-436" data-price-amount="45" data-price-type="finalPrice" class="price-wrapper "><span class="price"><?= $item['description'] ?></span></span>
                                    </span>
                                </span>
                            </div>
                        </div>
                    </div>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ol>
</div>


<script type="text/javascript">
    require(['jquery', 'slick'], function($) {
        $(function() {
            $('.my-list').slick({
                dots: true,
                infinite: true,
                autoplay : true,
                autoplaySpeed: <?= $timeScrollSlide*1000 ?>,
                slidesToShow: <?= $numSlide ?>,
                slidesToScroll: <?= $numScrollSlide ?>,
                arrows: true
            });
        });
    });
</script>